-- store
DROP TABLE IF EXISTS store;
CREATE TABLE store (
                       store_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       store_name VARCHAR NOT NULL,
                       address VARCHAR NOT NULL,
                       tel VARCHAR NULL,
                       buz_no VARCHAR NULL,
                       store_type varchar NOT NULL,
                       login_id VARCHAR NOT NULL,
                       password VARCHAR NOT NULL
);

CREATE INDEX idx_store ON store (store_id);

-- orders
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
                        order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        store_id BIGINT NOT NULL,
                        total_price INT NULL,
                        order_time TIMESTAMP NULL,
                        complete integer,
                        FOREIGN KEY (store_id) REFERENCES store(store_id)
);

CREATE INDEX idx_orders ON orders (order_id);

-- menu
DROP TABLE IF EXISTS menu;
CREATE TABLE menu (
                      menu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      store_id BIGINT NOT NULL,
                      menu_name VARCHAR NOT NULL,
                      menu_type VARCHAR NOT NULL,
                      price INT NOT NULL,
                      FOREIGN KEY (store_id) REFERENCES store(store_id)
);

CREATE INDEX idx_menu ON menu (menu_id);

-- order_detail (외래 키를 변경된 'orders' 테이블과 연결)
DROP TABLE IF EXISTS order_detail;
CREATE TABLE order_detail (
                              detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              order_id BIGINT NOT NULL,
                              menu_name VARCHAR NOT NULL,
                              price INT NOT NULL,
                              FOREIGN KEY (order_id) REFERENCES orders(order_id)  -- 'orders' 테이블과 참조
);

CREATE INDEX idx_order_detail ON order_detail (detail_id);

-- ai
DROP TABLE IF EXISTS ai;
CREATE TABLE ai (
                    ai_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    store_id BIGINT NOT NULL,
                    ai_date DATE NOT NULL,
                    region VARCHAR NOT NULL,
                    total_result TEXT NOT NULL,
                    com_result TEXT NOT NULL,
                    order_result TEXT NOT NULL,
                    FOREIGN KEY (store_id) REFERENCES store(store_id)
);

CREATE INDEX idx_ai ON ai (ai_id);